title: Jerry Yin Homepage
page-top-title: Jerry Yin Homepage
top-section-bg-text: A Dedicated NLP & ML System Nerd Dreaming of AGI World
home-subtitle: Jerry Yin
copyright-text: '&copy; Jerry Yin 2024. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
